server:
  port: 10300

spring:
  application:
    name: cloud-penguins-workflow
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: { NACOS_HOST:localhost:8848 }
        namespace: penguins
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/penguins_workflow?nullCatalogMeansCurrent=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

