server:
  port: 11011

spring:
  application:
    name: cloud-penguins-auth
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/penguins_auth?nullCatalogMeansCurrent=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl