server:
  port: 11011

spring:
  profiles:
    active: dev
  application:
    name: cloud-penguins-auth
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/penguins_auth?nullCatalogMeansCurrent=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: penguins
      config:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
